# Generated by Django 6.0.4 on 2026-04-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ', 'verbose_name_plural': 'Hồ sơ'},
        ),
    ]
