# Generated by Django 6.0.4 on 2026-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(default='Chưa cập nhật', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
