# Generated by Django 6.0.4 on 2026-05-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Lịch hẹn', 'verbose_name_plural': 'Lịch hẹn'},
        ),
    ]
